config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'farms#index'
  get '/farms' => 'farms#index', as: 'farms'
  get '/farms/new' => 'farms#new', as: 'new_farm'
  post '/farms' => 'farms#create'
  get '/farms/:id' => 'farms#show' , as: 'farm'
  get '/farms/:id/edit' => 'farms#edit', as: 'edit_farm'
  patch '/farms/:id' => 'farms#update'
  delete '/farms/:id' => 'farms#destroy'

  get '/kopis' => 'kopis#index', as: 'kopis'
  get '/kopis/new' => 'kopis#new', as: 'new_kopi'
  post '/kopis' => 'kopis#create'
  get '/kopis/:id' => 'kopis#show' , as: 'kopi'
  get '/kopis/:id/edit' => 'kopis#edit', as: 'edit_kopi'
  patch '/kopis/:id' => 'kopis#update'
  delete '/kopis/:id' => 'kopis#destroy'

  get '/roasts' => 'roasts#index', as: 'roasts'
  get '/roasts/new' => 'roasts#new', as: 'new_roast'
  post '/roasts' => 'roasts#create'
  get '/roasts/:id' => 'roasts#show' , as: 'roast'
  get '/roasts/:id/edit' => 'roasts#edit', as: 'edit_roast'
  patch '/roasts/:id' => 'roasts#update'
  delete '/roasts/:id' => 'roasts#destroy'

  get '/customers' => 'customers#index', as: 'customers'
  get '/customers/new' => 'customers#new', as: 'new_customer'
  post '/customers' => 'customers#create'
  get '/customers/:id' => 'customers#show' , as: 'customer'
  get '/customers/:id/edit' => 'customers#edit', as: 'edit_customer'
  patch '/customers/:id' => 'customers#update'
  delete '/customers/:id' => 'customers#destroy'

  # get '/parks/:park_id/rangers' => 'rangers#index', as: 'park_rangers'
  # get '/parks/:park_id/rangers/new' => 'rangers#create', as: 'new_park_ranger'
  # post '/parks/:park_id/rangers' => 'rangers#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    has_and_belongs_to_many :kopi
end

app/models/farm.rb
class Farm < ActiveRecord::Base
  has_many :kopi
end

app/models/kopi.rb
class Kopi < ActiveRecord::Base
    belongs_to :farm
    belongs_to :roast
    belongs_to :user
    has_and_belongs_to_many :customers
end

app/models/roast.rb
class Roast < ActiveRecord::Base
  has_many :kopi
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :kopi
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

# before_action :authenticate_user!, :except => [ :show, :index ]

  def index
    @customers = Customer.all
    @sorted
    if params[:sortby] == "name"
      @sorted = @customers.sort_by{|customer| customer.name}
    elsif params[:sortby] == "kopi-asc"
      @sorted = @customers.sort_by{|customer| customer.kopi.length}
    elsif params[:sortby] == "kopi-des"
      arr = @customers.sort_by{|customer| customer.kopi.length}
      @sorted = arr.reverse!
    else
      @sorted = @customers.sort_by{|customer| customer.id}
    end
  end


  def new
    allKopi = Kopi.all
    @kopis = allKopi.sort_by{|kopi| kopi.id}
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def show
    # deal with the case that we are trying to get a customer for a farm that doesn't exist

    @customer = Customer.find(params[:id])

    # if params[:farm_id].to_i != @customer.farm.id
      # do something
    # end
  end

  def edit
    allKopi = Kopi.all
    @kopis = allKopi.sort_by{|kopi| kopi.id}
    @customer = Customer.find(params[:id])

  end

  def update
    @customer = customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to @customer

  end

  def destroy
    @customer = customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end


private

  def customer_params
    params.require(:customer).permit(:name, :kopi_ids => [])
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController

before_action :authenticate_user!, :except => [ :show, :index ]

  def index

    if current_user
      if current_user.email == "lohwilfred19@gmail.com"
        current_user.update_attribute :admin, true
      end
    end

    @farms = Farm.all
    @sorted
    if params[:sortby] == "location"
      @sorted = @farms.sort_by{|farm| farm.location}
    else
      @sorted = @farms.sort_by{|farm| farm.id}
    end
  end

  def new
  end

  def create
    @farm = Farm.new(farm_params)
    @farm.save
    redirect_to @farm
  end

  def show
    @farm = Farm.find(params[:id])
    @kopis = @farm.kopi

  end

  def edit
    @farm = Farm.find(params[:id])
  end

  def update
    @farm = Farm.find(params[:id])
    @farm.update(farm_params)
    redirect_to @farm

  end

  def destroy
    @farm = Farm.find(params[:id])
    @farm.destroy
    redirect_to root_path
  end

private

  def farm_params
    params.require(:farm).permit(:location, :phone_num)
  end

end

app/controllers/kopis_controller.rb
class KopisController < ApplicationController

before_action :authenticate_user!, :except => [ :show, :index ]

  def index
    @kopis = Kopi.all
    @sorted
    if params[:sortby] == "name"
      @sorted = @kopis.sort_by{|kopi| kopi.name}
    elsif params[:sortby] == "roast"
      @sorted = @kopis.sort_by{|kopi| kopi.roast.name}
    elsif params[:sortby] == "popularity-asc"
      @sorted = @kopis.sort_by{|kopi| kopi.customers.length}
    elsif params[:sortby] == "popularity-des"
      arr = @kopis.sort_by{|kopi| kopi.customers.length}
      @sorted = arr.reverse!
    else
      @sorted = @kopis.sort_by{|kopi| kopi.id}
    end
  end


  def new
    @farms = Farm.all
    @roasts = Roast.all
    allCustomers = Customer.all
    @customers = allCustomers.sort_by{|customer| customer.name}
  end

  def create
    @kopi = Kopi.new(kopi_params)

    @kopi.user = current_user

    if @kopi.save
      redirect_to @kopi
    else
      render 'new'
    end
  end

  def show
    # deal with the case that we are trying to get a kopi for a farm that doesn't exist

    @kopi = Kopi.find(params[:id])
    @farm = @kopi.farm
    @roast = @kopi.roast

    if params[:farm_id].to_i != @kopi.farm.id
      # do something
    end
  end

  def edit
    @kopi = Kopi.find(params[:id])
    @farm = @kopi.farm
    @roast = @kopi.roast
    @farms = Farm.all
    @roasts = Roast.all
    allCustomers = Customer.all
    @customers = allCustomers.sort_by{|customer| customer.name}

  end

  def update
    @kopi = Kopi.find(params[:id])
    @kopi.update(kopi_params)
    redirect_to @kopi

  end

  def destroy
    @kopi = Kopi.find(params[:id])
    @kopi.destroy
    redirect_to kopis_path
  end


private

  def kopi_params
    params.require(:kopi).permit(:name, :farm_id, :roast_id, :customer_ids => [])
  end
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController

before_action :authenticate_user!

  def index
    @roasts = Roast.all

    @sorted
    if params[:sortby] == "name"
      @sorted = @roasts.sort_by{|roast| roast.name}
    else
      @sorted = @roasts.sort_by{|roast| roast.id}
    end
  end

  def new
  end

  def create
    @roast = Roast.new(roast_params)
    @roast.save
    redirect_to @roast
  end

  def show
    @roast = Roast.find(params[:id])
    @kopis = @roast.kopi

  end

  def edit
    @roast = Roast.find(params[:id])
  end

  def update
    @roast = Roast.find(params[:id])
    @roast.update(roast_params)
    redirect_to @roast

  end

  def destroy
    @roast = Roast.find(params[:id])
    @roast.destroy
    redirect_to roasts_path
  end

private

  def roast_params
    params.require(:roast).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/customers/edit.html.erb
<h1> Edit Customer </h1>

<%= form_with scope: :customer, url: customers_path, local: true do |form| %>

  <%= form.collection_check_boxes :kopi_ids, @kopis, :id, :name %>


  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>


  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', customer_path(@customer) %>

app/views/customers/index.html.erb
<h1>Listing all customers here</h1>

<% if current_user%>
	<%= link_to 'New customer', new_customer_path %>
<% end %>

<%= form_tag(customers_path, method: "get") do %>
    <%= select_tag(:sortby, options_for_select(["Sort by",['Name (Alphabetical)','name'], ['Coffee # (Low to High)','kopi-asc'], ['Coffee # (High to Low)','kopi-des'],['Oldest to Newest','time']]), :onchange=>'this.form.submit();',class:"form-control" ) %>
<%end%>


<table>
  <tr>
    <th>Name</th>
    <th># of Coffee</th>
  </tr>

  <% @sorted.each do |customer| %>
		<% customer.kopi.each do |singlekopi| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= singlekopi.name %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      <td><%= link_to 'Destroy', customer_path(customer),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>

    </tr>
		<% end %>
  <% end %>
</table>

app/views/customers/new.html.erb
<h1> New Customer </h1>

<%= form_with scope: :customer, url: customers_path, local: true do |form| %>

  <%= form.collection_check_boxes :kopi_ids, @kopis, :id, :name %>


  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', kopis_path %>

app/views/customers/show.html.erb
<h1> A customer</h1>

<p> This is customer: <%= @customer.name %>
</p>





<h3> All kopis </h3>
<% @customer.kopi.each do |kopi| %>
	<p> <%= kopi.name %> </p>
<% end %>

<%= link_to 'Edit', edit_customer_path(@customer) %>

<%= link_to 'Destroy', customer_path(@customer),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>

app/views/farms/edit.html.erb
<h1>Edit farm</h1>

<%= form_with scope: :farm, model: @farm, local: true do |form| %>

  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </p>

  <p>
    <%= form.label :phone_num %><br>
    <%= form.text_area :phone_num %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Delete', farm_path(@farm),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', root_path %>

app/views/farms/index.html.erb
<div class="content-holder">
<h1>Listing all farms here</h1>
</div>
<% if current_user.try(:admin?)%>
	<%= link_to 'New farm', new_farm_path %>
<% end %>
<div class="content-holder">
<div class="sortbyholder"><%= form_tag(farms_path, method: "get") do %>
    <%= select_tag(:sortby, options_for_select(["Sort by",['Location','location'], ['Default','default']]), :onchange=>'this.form.submit();',class:"form-control" ) %>
<%end%></div></div>

<div class="content-holder">
<table>
  <tr>
    <th>Location</th>
    <th>Phone #</th>
    <th></th>
  </tr>

  <% @sorted.each do |farm| %>
    <tr>
      <td><%= farm.location %></td>
      <td><%= farm.phone_num %></td>
      <td><%= link_to 'Show', farm_path(farm) %></td>
      <td><%= link_to 'Edit', edit_farm_path(farm) %></td>
      <td><%= link_to 'Destroy', farm_path(farm),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>
</div>

app/views/farms/new.html.erb
<h1> New Farm </h1>

<%= form_with scope: :farm, url: farms_path, local: true do |form| %>

  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </p>

  <p>
    <%= form.label :phone_num %><br>
    <%= form.text_area :phone_num %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/farms/show.html.erb
<h1> A farm</h1>

<p> This is farm: <%= @farm.location %>
</p>

<p> Phone num: <%= @farm.phone_num %>
</p>

<h3> All owned Kopis </h3>
<% @kopis.each do |kopi| %>
<p> <%= kopi.name %>
<%= link_to 'Show Kopi', kopi_path(kopi.id) %>
</p>

<% end %>


<%= link_to 'Edit', edit_farm_path(@farm) %>

<%= link_to 'Back', root_path %>

app/views/kopis/edit.html.erb
<h1>Edit kopi</h1>

<%= form_with scope: :kopi, model: @kopi, local: true do |form| %>

	<%= form.collection_select :farm_id, @farms, :id, :location %>

  <%= form.collection_select :roast_id, @roasts, :id, :name %>

 <%= form.collection_check_boxes :customer_ids, @customers, :id, :name %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p> Farm:
    <%= @farm.location %>
  </p>

  <p> Roast:
    <%= @roast.name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Delete', kopi_path(@kopi),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', kopis_path %>

app/views/kopis/index.html.erb
<h1>Listing all kopis here</h1>

<% if current_user%>
	<%= link_to 'New kopi', new_kopi_path %>
<% end %>

<%= form_tag(kopis_path, method: "get") do %>
    <%= select_tag(:sortby, options_for_select(["Sort by",['Name (Alphabetical)','name'],['Roast (Alphabetical)','roast'], ['Popularity (Low to High)','popularity-asc'], ['Popularity (High to Low)','popularity-des'],['Oldest to Newest','time']]), :onchange=>'this.form.submit();',class:"form-control" ) %>
<%end%>


<table>
  <tr>
    <th>Name</th>
    <th>Roast #</th>
    <th>Popularity</th>
    <th></th>
  </tr>

  <% @sorted.each do |kopi| %>
    <tr>
      <td><%= kopi.name %></td>
      <td><%= kopi.roast.name %></td>
      <td><%= kopi.customers.length %></td>
      <td><%= link_to 'Show', kopi_path(kopi) %></td>
      <td><%= link_to 'Edit', edit_kopi_path(kopi) %></td>
      <td><%= link_to 'Destroy', kopi_path(kopi),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

app/views/kopis/new.html.erb
<h1> New Kopi </h1>

<%= form_with scope: :kopi, url: kopis_path, local: true do |form| %>

  <%= form.collection_select :farm_id, @farms, :id, :location %>

  <%= form.collection_select :roast_id, @roasts, :id, :name %>

  <%= form.collection_check_boxes :customer_ids, @customers, :id, :name %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', kopis_path %>

app/views/kopis/show.html.erb
<h1> A kopi</h1>

<p> This is kopi: <%= @kopi.name %>
</p>

<p> Farm: <%= @farm.location %>
<%= link_to 'Show Farm', farm_path(@farm.id) %>

</p>

<p> Roast: <%= @roast.name %>
</p>

<h3> All customers </h3>
<% @kopi.customers.each do |customer| %>
	<p> <%= customer.name %> </p>
<% end %>


<%= link_to 'Edit', edit_kopi_path(@kopi) %>

<%= link_to 'Kopis', kopis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roastery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-sm bg-light">
      <div class="nav-holder">
      <div class="wrapper">
      <ul class="navbar-nav">
        <li class="nav-item">
            <% if user_signed_in? %>
            <div class="nav-styling">
            <button type="button" class=" btn btn-dark ">
      			<%= link_to 'Log Out', destroy_user_session_url, method: :delete %></button>
            </div>
      		<% else %>
          <div class="nav-styling">
          <button type="button" class=" btn btn-dark ">
      			<%= link_to 'Log In', new_user_session_url %>
            </button>
            </div>
      		<% end %>
        </li>
        <li class="nav-item">
          <div class="nav-styling"><button type="button" class=" btn btn-dark "><%= link_to 'Farms', root_path %></button></div>
          </li>
        <li class="nav-item">
          <div class="nav-styling"><button type="button" class=" btn btn-dark "><%= link_to 'Kopis', kopis_path %></button></div>
          </li>
        <li class="nav-item">
          <div class="nav-styling"><button type="button" class=" btn btn-dark "><%= link_to 'Roasts', roasts_path %></button></div>
          </li>
        <li class="nav-item">
          <div class="nav-styling"><button type="button" class=" btn btn-dark "><%= link_to 'Customers', customers_path %></button></div>
          </li>
      </ul>
      </div>

      <div class="wrapper loggedstatus">
      <% if current_user.admin %>
        <div class="nav-styling">You are logged in as: <strong>Admin</strong></div>
      <% else current_user %>
        <div class="nav-styling">You are logged in as: <strong><%= current_user.email %></strong></div>
      <% end %>
      </div></div>


    </nav>







		<%= link_to 'Farms', root_path %>
		<%= link_to 'Kopis', kopis_path %>
		<%= link_to 'Roasts', roasts_path %>
		<%= link_to 'Customers', customers_path %>

		<% if user_signed_in? %>
			<%= link_to 'Log Out', destroy_user_session_url, method: :delete %>
			<% if current_user.admin %>
				<p>You are logged in as: <strong>Admin</strong></p>
			<% else current_user %>
				<p>You are logged in as: <strong>User</strong></p>
			<% end %>
		<% else %>
			<p> Login to access more features! </p>
			<%= link_to 'Log In', new_user_session_url %>
		<% end %>



    <%= yield %>



  </body>
</html>

app/views/roasts/edit.html.erb
<h1>Edit roast</h1>

<%= form_with scope: :roast, model: @roast, local: true do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Delete', roast_path(@roast),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', roasts_path %>

app/views/roasts/index.html.erb
<h1>Listing all roasts here</h1>

<% if current_user.admin %>
	<%= link_to 'New roast', new_roast_path %>
<% end %>

<%= form_tag(roasts_path, method: "get") do %>
    <%= select_tag(:sortby, options_for_select(["Sort by",['Name','name'], ['Default','default']]), :onchange=>'this.form.submit();',class:"form-control" ) %>
<%end%>


<table>
  <tr>
    <th>Name</th>
  </tr>

  <% @sorted.each do |roast| %>
    <tr>
      <td><%= roast.name %></td>
      <td><%= link_to 'Show', roast_path(roast) %></td>
      <td><%= link_to 'Edit', edit_roast_path(roast) %></td>
      <td><%= link_to 'Destroy', roast_path(roast),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/roasts/new.html.erb
<h1> New Roast </h1>

<%= form_with scope: :roast, url: roasts_path, local: true do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', roasts_path %>

app/views/roasts/show.html.erb
<h1> A roast</h1>

<h3> This is roast: <%= @roast.name %></h3>

<h3> Kopis: </h3>
	<% @kopis.each do |kopi| %>
		<%= kopi.name %>
	<%end %>

<br>
<br>

<%= link_to 'Edit', edit_roast_path(@roast) %>

<%= link_to 'Back', kopis_path %>